FROM node:alpine

ARG NODE_ENV
ARG MYSQL_HOST
ARG MYSQL_ROOT_PASSWORD
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_DATABASE

ENV NODE_ENV=%NODE_ENV
ENV MYSQL_HOST=$MYSQL_HOST
ENV MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD
ENV MYSQL_DATABASE=$MYSQL_DATABASE

WORKDIR /usr/src/app

COPY . .

RUN npm install
# RUN npm install pm2
RUN npm run production:build

EXPOSE 3000

CMD [ "npm", "run", "production:start" ]
