version: "3"
services:
  proxy:
    image: nginx
    container_name: proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
    depends_on:
      - server
      - db

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server
    networks:
      - backend
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    env_file: .env
    environment:
      NODE_ENV: production
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    restart: always
    stdin_open: true # for keep open the terminal after building container
    tty: true # for keep open the terminal after building container
    depends_on:
      - db

  db:
    build:
      context: ./deploy
      dockerfile: Dockerfile.mysql
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - backend
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
    volumes:
      - datavolume:/var/lib/mysql

networks:
  backend:
    driver: bridge

volumes:
  datavolume:
