name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

env:
  TESTING_MYSQL_DATABASE: test_db
  TESTING_MYSQL_USER: root
  TESTING_MYSQL_PASSWORD: root
  TESTING_MYSQL_ROOT_PASSWORD: rootpassword
  TESTING_MYSQLDB_LOCAL_PORT: 3306
  ACCESS_TOKEN_SECRET: 3a39f0286e3a93c9c58e8a4194d23bbc34fd7075b8fd975123d96707050563af53d950ee1831740e7679e8d9c319799551058cb7baf1d6582791096ef6de5f25
  REFRESH_TOKEN_SECRET: 5791470e7257a304123aab40eb168a62e75eec0392c334d50de306ab5bd4615c1d6e588c9ba62e36298c873a1696591d01ee16322636c986679e9bf9d41c9812

jobs:
  TESTING_REST_API:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set up MySQL
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE ${{ env.TESTING_MYSQL_DATABASE }};' -u${{ env.TESTING_MYSQL_USER }} -p${{ env.TESTING_MYSQL_PASSWORD }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests
        run: |
          npm run test:workflow